import { address } from "@solana/kit";
import path from "path";
import fs from "fs";
import dotenv from "dotenv";
import {
  type CircuitConfig,
  type ProofResult,
  getProverTomlPath,
  compileCircuit,
  generateWitness,
  compileCcs,
  setupKeys,
  generateGroth16Proof,
  readProofFiles,
  createInstructionData,
} from "@solana-noir-examples/lib/proof";
import {
  verifyOnChain,
  printTransactionResult,
  handleVerifyError,
} from "@solana-noir-examples/lib/verify";

// @dev - Import Poseidon and Sparse Merkle Tree utilities for nullifier computation from the smt.ts
import { initPoseidon, poseidonHash2, fieldToHex } from "./utils/poseidon-and-merkle-tree/smt";

// Load environment variables from .env file
dotenv.config({ path: path.join(process.cwd(), "..", ".env") });

const RPC_URL = process.env.RPC_URL || "https://api.testnet.solana.com";

// Get the deployed Groth16 verifier program ID from environment variable
const PROGRAM_ID =
  process.env.ZK_GROTH16_VERIFIER_PROGRAM_ID ||
  "EK3F1ZwnEPcvCtLk1wuEHdFqhJE7rpBoxpFrw5uU9zTR";

const circuitConfig: CircuitConfig = {
  circuitDir: path.join(process.cwd(), ".."),
  circuitName: "payroll_backed_loan",
};

const walletPath =
  process.env.SOLANA_KEYPAIR ||
  path.join(
    process.env.HOME || "",
    ".config",
    "solana",
    "solana-deployer-keypair.json"
  );

// Payroll-Backed Loan Circuit Inputs
export interface PayrollBackedLoanInputs {
  // Public inputs
  nullifier: string;

  // Private inputs - zkTLS Proof of payroll
  payroll_proof: string[];
  payroll_amount: number;
  employment_status: boolean;
  hire_date: number;
  current_date: number;

  // Private inputs - Loan eligibility
  min_payroll_amount: number;
  payroll_history: string[];
  repayment_ratio: number;
  loan_amount: number;
  jurisdiction_code: string;
  allowed_jurisdiction_root: string;
  jurisdiction_merkle_proof: string[];
}

function formatFieldArray(fields: string[]): string {
  const lines: string[] = [];
  for (let i = 0; i < fields.length; i += 10) {
    const chunk = fields.slice(i, i + 10);
    lines.push("    " + chunk.map((f) => `"${f}"`).join(", "));
  }
  return "[\n" + lines.join(",\n") + "\n]";
}

export function writePayrollProverToml(
  config: CircuitConfig,
  inputs: PayrollBackedLoanInputs
): void {
  const toml = `# Payroll-Backed Loan Proof - Generated by client

# Public inputs
[public_inputs]
nullifier = "${inputs.nullifier}"

# Private inputs
[private_inputs]
# zkTLS Proof of payroll
payroll_proof = ${formatFieldArray(inputs.payroll_proof)}
payroll_amount = "${inputs.payroll_amount}"
employment_status = ${inputs.employment_status}
hire_date = "${inputs.hire_date}"
current_date = "${inputs.current_date}"

# Loan eligibility
min_payroll_amount = "${inputs.min_payroll_amount}"
payroll_history = ${formatFieldArray(inputs.payroll_history)}
repayment_ratio = "${inputs.repayment_ratio}"
loan_amount = "${inputs.loan_amount}"
jurisdiction_code = "${inputs.jurisdiction_code}"
allowed_jurisdiction_root = "${inputs.allowed_jurisdiction_root}"
jurisdiction_merkle_proof = ${formatFieldArray(inputs.jurisdiction_merkle_proof)}
`;
  fs.writeFileSync(getProverTomlPath(config), toml);
}

export function generateProof(
  config: CircuitConfig,
  inputs: PayrollBackedLoanInputs
): ProofResult {
  writePayrollProverToml(config, inputs);
  // Recompile circuit to ensure ACIR is fresh
  compileCircuit(config);
  generateWitness(config);
  // Regenerate CCS and keys to match the new witness
  compileCcs(config);
  setupKeys(config);
  generateGroth16Proof(config);
  return readProofFiles(config);
}

// Test values matching the test_payroll_backed_loan.nr test
// Note: nullifier is computed as poseidon_hash_2(jurisdiction_code, allowed_jurisdiction_root)
function createTestValues(): PayrollBackedLoanInputs {
  const jurisdiction_code = "1"; // Example: USA
  const allowed_jurisdiction_root = "12345";
  
  // Compute nullifier: poseidon_hash_2(jurisdiction_code, allowed_jurisdiction_root)
  const nullifier = fieldToHex(poseidonHash2(BigInt(jurisdiction_code), BigInt(allowed_jurisdiction_root)));

  return {
    // Public inputs
    nullifier,

    // Private inputs - zkTLS Proof of payroll
    payroll_proof: Array(64).fill("0"),
    payroll_amount: 5000, // $5,000/month
    employment_status: true,
    hire_date: 20000, // timestamp in days
    current_date: 20360, // ~12 months later

    // Private inputs - Loan eligibility
    min_payroll_amount: 3000, // $3,000/month minimum
    payroll_history: [
      ...Array(12).fill("5000"), // 12 months of $5,000 payroll
      ...Array(20).fill("0"), // Fill remaining 20 slots with 0
    ],
    repayment_ratio: 2, // Can borrow up to 2x monthly salary
    loan_amount: 10000, // $10,000 loan request
    jurisdiction_code,
    allowed_jurisdiction_root,
    jurisdiction_merkle_proof: Array(32).fill("0"),
  };
}

let TEST_VALUES: PayrollBackedLoanInputs;

function printUsage() {
  console.log(`
Usage: npm run verify:payroll -- [options]

Options:
  --program <id>     Verifier program ID (default: ${PROGRAM_ID})
  --corrupt          Corrupt proof to test verifier rejects invalid proofs
  --rpc <url>        RPC URL (default: ${RPC_URL})

Examples:
  npm run verify:payroll
  npm run verify:payroll -- --program <PROGRAM_ID>
  npm run verify:payroll -- --corrupt   # Should fail - proves verifier works
  npm run verify:payroll -- --rpc https://api.mainnet-beta.solana.com

Environment Variables:
  ZK_GROTH16_VERIFIER_PROGRAM_ID  Program ID of the deployed verifier
  SOLANA_KEYPAIR                  Path to wallet keypair file
  RPC_URL                         Solana RPC URL
`);
}

async function main() {
  console.log("Payroll-Backed Loan - Solana ZK Verifier Client\n");
  console.log(
    "Proves: Employee is eligible for a payroll-backed loan based on:\n"
  );
  console.log("  - Active employment status");
  console.log("  - Sufficient payroll amount");
  console.log("  - Minimum tenure requirement");
  console.log("  - Consistent payroll history");
  console.log("  - Loan affordability based on repayment ratio\n");

  // Initialize Poseidon and compute test values
  await initPoseidon();
  TEST_VALUES = createTestValues();

  const args = process.argv.slice(2);

  if (args.includes("--help") || args.includes("-h")) {
    printUsage();
    process.exit(0);
  }

  const corrupt = args.includes("--corrupt");

  const programIdx = args.indexOf("--program");
  const programIdStr = programIdx !== -1 ? args[programIdx + 1] : PROGRAM_ID;
  const programId = address(programIdStr);

  const rpcIdx = args.indexOf("--rpc");
  const rpcUrl = rpcIdx !== -1 ? args[rpcIdx + 1] : RPC_URL;

  try {
    console.log("=== Test Scenario ===");
    console.log(`Payroll: $${TEST_VALUES.payroll_amount}/month`);
    console.log(`Loan Request: $${TEST_VALUES.loan_amount}`);
    console.log(`Employment Status: ${TEST_VALUES.employment_status ? "Active" : "Inactive"}`);
    console.log(`Tenure: ${TEST_VALUES.current_date - TEST_VALUES.hire_date} days (~12 months)`);
    console.log(`Min Required Payroll: $${TEST_VALUES.min_payroll_amount}/month`);
    console.log(`Repayment Ratio: ${TEST_VALUES.repayment_ratio}x monthly salary`);
    console.log(
      `Max Loan Allowed: $${TEST_VALUES.payroll_amount * TEST_VALUES.repayment_ratio}\n`
    );

    console.log("Generating payroll-backed loan proof...\n");

    const proofResult = generateProof(circuitConfig, TEST_VALUES);

    if (corrupt) {
      console.log("⚠️  CORRUPTING PROOF FOR TESTING\n");
      proofResult.proof[0] ^= 0xff;
    }

    console.log(`Proof size: ${proofResult.proof.length} bytes`);
    console.log(`Witness size: ${proofResult.publicWitness.length} bytes`);

    const instructionData = createInstructionData(proofResult);
    console.log(`Total instruction data: ${instructionData.length} bytes\n`);

    const sig = await verifyOnChain(instructionData, {
      rpcUrl,
      programId,
      walletPath,
      computeUnits: 800_000, // Higher compute units for complex circuit
    });

    console.log("\n✅ Payroll-backed loan proof verified on-chain!");
    
    // Determine cluster from RPC URL
    const cluster = rpcUrl.includes("testnet")
      ? "testnet"
      : rpcUrl.includes("devnet")
      ? "devnet"
      : "mainnet-beta";
    
    printTransactionResult(sig, cluster);
  } catch (err) {
    handleVerifyError(err);
  }
}

main();
