[package]
name = "sanction_checker"
type = "lib"
authors = [""]
#compiler_version = "1.0.0-beta.18"

[dependencies]
date = { tag = "v0.5.6", git = "https://github.com/madztheo/noir-date.git" }
sanctions = { path = "./forked_libs/zkpassport/exclusion-check/sanctions" }
utils = { path = "./forked_libs/zkpassport/utils" }
validity_check = { path = "./forked_libs/provekit/passport_validity_check" }
commitment_utils = { path = "./forked_libs/zkpassport/commitment/common" }
expiry_check = { path = "./forked_libs/zkpassport/data-check/expiry" }
rsa_sig_check = { path = "./forked_libs/provekit/zkpassport_libs/sig-check/rsa" }
tbs_check = { path = "./forked_libs/provekit/zkpassport_libs/data-check/tbs-pubkey" }