[package]
name = "payroll_backed_loan"
type = "bin"
authors = [""]
version = "0.0.1"

[dependencies]
# Poseidon hash function for Noir
poseidon = { tag = "v0.1.1", git = "https://github.com/noir-lang/poseidon" }

# OFAC compliance check library (NOTE: Since the dependencies of this library is adjusted for Noir v0.34.0, we should consider to use this library as it is)
sanction_checker = { path = "../sanction_checker" }